### ISSUE TITLE
Cargo rmc configuration in Config.toml should support standard tables

### ISSUE THREAD

**Issue by celinval** [model-checking/rmc#739]
Requested feature: Users should be able to set rmc flags via Cargo.toml tables [package.metadata](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table) and [workspace.metadata](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacemetadata-table).
Use case: Users may want to add to their Cargo.toml configuration flags on how to run rmc for their proof harnesses. Today we support configuration via `[rmc]` table inside toml files, but when added to Cargo.toml, this table generates a warning. To avoid that, we should support the standard places defined by Cargo.
Link to relevant documentation (Rust reference, Nomicon, RFC):
Is this a breaking change? No

Test case:

```rust
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

#[cfg(rmc)]
mod rmc_tests {
    #[rmc::proof]
    fn check_config() {
        let mut counter = 0;
        while rmc::any() {
            counter += 1;
            assert!(counter < 10, "Cargo.toml should've configure rmc to stop at iteration 5");
        }
    }
}
```

and Cargo.toml

```toml
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
[package]
name = "check_config"
version = "0.1.0"
edition = "2018"

[dependencies]

[package.metadata.rmc]
flags={unwind = "5", unwinding-checks = false, function="check_config"}
```
